Enum entry constructor custom test
Expected class org.jetbrains.kotlin.analysis.api.symbols.KaClassSymbol instead of class org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirEnumEntrySymbol for org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirEnumEntrySymbol@44fb3090
java.lang.IllegalArgumentException: Expected class org.jetbrains.kotlin.analysis.api.symbols.KaClassSymbol instead of class org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirEnumEntrySymbol for org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirEnumEntrySymbol@44fb3090
	at org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirConstructorSymbol.createPointer(KaFirConstructorSymbol.kt:523)
	at org.jetbrains.kotlin.analysis.api.fir.test.EnumEntryConstructorPointerTest$enumEntryWithBodyConstructorPointerInIgnoreSelfMode$1$pointer$1.invoke(EnumEntryConstructorPointerTest.kt:62)
	at org.jetbrains.kotlin.analysis.api.fir.test.EnumEntryConstructorPointerTest$enumEntryWithBodyConstructorPointerInIgnoreSelfMode$1$pointer$1.invoke(EnumEntryConstructorPointerTest.kt:60)
	at org.jetbrains.kotlin.analysis.api.impl.base.symbols.pointers.KaBasePsiSymbolPointer$Companion.withDisabledPsiBasedPointers(KaBasePsiSymbolPointer.kt:106)
	at org.jetbrains.kotlin.analysis.api.fir.test.EnumEntryConstructorPointerTest$enumEntryWithBodyConstructorPointerInIgnoreSelfMode$$inlined$analyzeCopy$1.invoke(analyze.kt:99)
	at org.jetbrains.kotlin.analysis.api.projectStructure.DanglingFilesKt.withDanglingFileResolutionMode(danglingFiles.kt:190)